server:
  host: 0.0.0.0
  port: 8004
  workers: 1
  log_level: info

model:
  repository: "ResembleAI/chatterbox"
  device: auto  # auto, cuda, mps, cpu
  default_voice: "Emily.wav"
  cache_dir: "./model_cache"

generation_defaults:
  temperature: 0.8
  exaggeration: 1.3
  cfg_weight: 0.5
  seed: 0
  speed_factor: 1.0
  language: en

audio_output:
  format: WAV
  sample_rate: 24000
  max_reference_duration: 30
  output_dir: "./outputs"

text_processing:
  chunk_size: 200
  max_length: 2000
  enable_splitting: true

twilio:
  account_sid: ""  # Set via environment variable TWILIO_ACCOUNT_SID
  auth_token: ""   # Set via environment variable TWILIO_AUTH_TOKEN
  phone_number: "" # Your Twilio phone number

llm:
  provider: anthropic  # anthropic or openai
  model: claude-3-5-sonnet-20241022
  api_key: ""  # Set via environment variable ANTHROPIC_API_KEY or OPENAI_API_KEY
  max_tokens: 150
  temperature: 0.7

security:
  enable_auth: false  # Set to true for production API key authentication
  username: admin
  password: ""  # DEPRECATED: Use environment variables instead
  enable_cors: true
  allowed_origins:
    - "http://localhost:3000"  # Frontend dev server
    - "http://localhost:8004"  # API docs
    # Add your production domains here for production deployment:
    # - "https://yourdomain.com"
    # - "https://app.yourdomain.com"
